### PR TITLE
Allow to visit structure without instance.

### PR DESCRIPTION
**Pull request by Jarod42**
Allow to visit structure member without instance.

### CODE REVIEW

**Comment by cbeck88** [comment]
This is a really nice PR. I like your proposed syntax, it fits very nicely with everything else, and it adds something pretty useful.

Before I merge it, I would like to:

- Extend it also so that it works for the "intrusive" syntax, and the hana / boost::fusion compatibility headers. IIUC this only does it for the basic version. I think it will all work the same way but it would be nice to check that before the merge.
- Possibly refactor it so that this visitation style is the "core", and the versions in which you have an instance are defined in terms of this one. It might be a little terser overall that way. (Actually this should happen after the merge.)
- Add a blurb about this to the README.md
- Run tests against two other projects that I have that use this code.

Thanks again.

**Comment by Jarod42** [comment]
Hi, after some manipulations to create json schema from structs, I found that

    template struct Tag {};

    v("a", Tag<int>{});

produces less template instantiations than

    v("a", my_struct::a);

And visitor syntax is then simpler (no use of member pointer).

**Comment by cbeck88** [comment]
Hi,

I guess they both have merits, but the member pointer can be used to implement the other one, and not vice versa.

I have written applications in the past where I wanted to be able to get the member pointers and found that I couldn't and had to redo things, so I'm sort of inclined to keep the member pointer version somehow.

Also, I see what you mean about having more template instantiations, since the struct itself has to be a template parameter then each time the visitor is invoked, but I'm inclined to think that it still is not going to be enough to cause problems.

I'm going to think about it a bit.

I think hana does something similar to what you suggest with `template <typename> struct type;` in namespace `hana`, and uses these in various places for tag disptach. But I don't know any other libraries that do that.

**Comment by Jarod42** [comment]
Having something  similar to member method might be useful.
Instead of member pointer, for *fusion*, getter can be used, something like:

            //-----------------------------------------------------------------------------
            template <typename Index>
            struct MemberValueGetter {
                template <typename T>
                auto operator ()(T&& t) const
                {
                    return boost::fusion::at<Index>(t);
                }
            };

            //-----------------------------------------------------------------------------
            template <typename V, typename T>
            class VisitorCallerWithoutInstanceWithGetter
            {
            public:
                explicit VisitorCallerWithoutInstanceWithGetter(V& v) : mVisitor(v) {}

                template <typename Index> void operator()(Index) const
                {
                    using type = MemberType<T, Index>;
                    mVisitor(GetMemberName<T, Index>(), Tag<type>{}, MemberValueGetter<Index>{});
                }

            private:
                V& mVisitor;
            };

        //-----------------------------------------------------------------------------
        // for
        // ```
        // struct S { int a; char c; std::string s;};
        // BOOST_FUSION_ADAPT_STRUCT(S, (int, a) (char, c) (std::string, s));
        // ```
        // `ApplyVisitorWithGetter<S>(v);` would be equivalent to:
        // ```
        // v("a", Tag<int>{}, GetterA);
        // v("c", Tag<char>{}, GetterC);
        // v("s", Tag<std::string>{}, GetterS);
        // ```
        template <typename T, typename V> void ApplyVisitorWithGetter(V&& v)
        {
            static_assert(is_visitable<T>::value, "BOOST_FUSION_ADAPT_STRUCT has not been called");

            details::VisitorCallerWithoutInstanceWithGetter<V&&, T> visitor{ v };
            boost::fusion::for_each(details::IndexSequence<T>(), visitor);
        }

**Comment by cbeck88** [comment]
Jarod42: I thought about a way to compromise on this.

So one way to accommodate both usages is, change the library so that it returns a "getter" function object instead of member pointer like you suggest.

But, the getter is also implicitly convertible to a member pointer.

This way old code is not broken, and the user can just select which type they want by changing the signature of the visitor appropriately.

And as you point out -- hana and fusion can be mostly compatible, since they both can give the getters at least. They still won't be able to give the member pointer but that's par for the course.

I don't think there's many situations where an implicit conversion like that would cause a problem, it's very rare that someone has a variable of member pointer type or a function that takes member pointers. Going to think about it some more though.

**Comment by cbeck88** [comment]
Hi Jarod42,

I merged several patches today so that the "getters" visitation, and the tag-dispatch for type visitation, are both supported.

Instead of `apply_visitor` without an instance, there are now three versions of it:

`visit_types` -- this passes `const char *, type_c<T>` when the member has type `T`
`visit_accessors` -- this passes `const char *, []() { ... }`, that is, an appropriate function object
`visit_pointers` -- this passes `const char *, T S::*` , as the original version.

The `apply_visitor` without an instance is now deprecated, and no longer documented, but it just calls `visit_pointers` as before to avoid breakage.

I have tested also that `visit_accessors` and `visit_types` does work, in the hana and fusion compat headers, with all tested compilers.

There are also now indexed getters, `get_accessor<idx, S>()`, and `get_pointer<idx, S>` which can grab the accessor object, or the member pointer, at a particular index in the list of fields.

**Pull request merged**
