### PR TITLE
Add "indexed" visitors

### PR DESCRIPTION
**Pull request by dcreager**
This patch adds a new set of visitor functions that include the index of the field within the struct, in addition to its name.  The indices are 0-based, and the field ordering is the same as the ordering of the parameters passed to the VISITABLE_STRUCT macro.

We also provide two new helpers in the visit_struct namespace.  One returns the number of fields in the struct, and the other gives you access to the field index enum.

### CODE REVIEW

**Comment by cbeck88** [comment]
Hi, I am currently on vacation, I will write in a few days after I looked at this. Thanks.

**Comment by dcreager** [comment]
No problem, thanks!

**Comment by cbeck88** [comment]
Ok, here are my initial thoughts:

I'm not totally sold on the "indexed visitors" thing. A very simple way that you can get the indices when you visit is to make a function object that contains a counter, and increments the counter each time it is called. It might look like this:

    template <typename V>
    struct indexing_visitor {
       V v;
       int idx;

        template <typename T>
       void operator()(const char * name, T && t) {
           std::forward<V>(v)(idx++, name, std::forward<T>(t));
       }
    };

    template <typename V, typename S>
    void apply_indexed_visitor(V && v , S && s) {
       indexing_visitor<V> v2{V, 0};
       visit_struct::apply_visitor(v2, std::forward<S>(s));
    }

Now, it's true that this doesn't have the enum thing, but at the same time, is the enum actually useful? Given a structure, I can't actually get the field corresponding to one of the enum values. Maybe there are some people who use one of these "better enum" libraries, and they'd like that better than having either the index or the `const char *` name I guess? Maybe `visit_struct` should ultimately use one of those as a dependency.

For the moment I'm just trying to keep the interface very small and avoid little details that you need to remember. For instance like, why does the `int` come before the `const char *` when doing an indexed visitor? Idk, that's the kind of thing I would always have to look up, and in different projects it could easily work differently.

---

I think having the field count be easily accessible at compile time is a good thing. In c++14 you can still get it at compile time, by applying a function object that just increments a counter. But in c++11 I think there is no way. And that might surely be useful I guess. So I would merge that for sure I think.

I thought also about, having an interface so that you can do like `visit_struct::at<2>(s)`, and it would get the second member of struct `s`. Or maybe `visit_struct::get<2>(s)`... That would let you use the structs similar to `std::tuple` and might be useful in some projects. I don't know, I didn't need this yet myself in anything I worked on.

Jarod42 commented something related yesterday though here: https://github.com/cbeck88/visit_struct/pull/3#issuecomment-306336489

I guess that both `hana` and `fusion` allow you to find the 1st, 2nd, etc. members at compile time, i.e. passing the index as a template parameter. So maybe we should support that too, and also let them get the number of members at compile-time, within C++11.

It occurred to me that you could try to simulate that within the existing `visit_struct::apply_visitor` framework; if you wanted to visit only the 3rd element, you could keep a counter and call the visitor only when you get to the third guy. But I don't think you can actually implement `std::get` this way, also, if your visitor is only defined for `int` or `std::string` etc. you would probably get a compiler error because of the elements you didn't intend to visit...

I don't know, is there a big advantage of the enums that you think I missed?

**Comment by dcreager** [comment]
Thanks for the comments!  I think I agree with your overall suggestion — just keep the `field_count` part, take out the indexed visitor part.  I'll push up a modified patch with that.

For background, our overall goal is to compare field names inside of a visitor, but without having to use a full string compare each time.  We have a helper class that lets us intern the strings, which would cause the field comparisons to be simple integer comparisons.  But we can't intern the field name inside of the visitor call, since that involves a hashing operation, and would be at least as expensive as the naive string comparison.

So, we wanted to use this indexed visitor to build up an array of interned field names for each struct, and another indexed visitor to compare field names by indexing into that array.  For both of those, we can use the "increment a field in the visitor" trick.

The other thing that the enum gives us is the ability to refer to fields at compile time by their name, instead of having to remember which integer index each field has.  But we're not actually using that feature right now, so I have no problems culling this patch to only include the `field_count` part.

As an aside, in an earlier version of this patch, I had a much more thorough `descriptor` struct for each field, instead of just an enum.  The descriptor contained the index, field name, and member pointer.  Ideally I would've modified the `apply_visitor` methods to take in this descriptor **instead** of the field name, since then you'd be able to pull out whichever parts of the descriptor that you needed.  But that was going to be a much more invasive, and backwards-incompatible, patch, and so I held off on it.

**Comment by dcreager** [comment]
Opened #7 containing just the `field_count` function.

**Comment by cbeck88** [comment]
Hi again,

You may be amused to learn, I have resurrected the "field_enum" in the `develop` branch.

I'm trying to extend the library so that users can use `std::tuple`-like methods with visitable structs. For instance, have `visit_struct::get<3>(s)` get the 4th element of the struct.

To my knowledge, there's no way to implement this using `apply_visitor`, so it ends up being a weakness of `visit_struct` if you need to do this.

I sort of held off on this for a long time because I didn't know a really good way to implement it without adding a lot of complexity. I know how to do things like, get the `i`'th element of a type-list using templates, but in the "basic" visit_struct library, there are no type-lists or variadic templates, it's all about the map macro. If the map macro were modified to pass indexes as well as the values, then it would be easy, but that would require complicating everything else.

Eventually I realized that your `enum` trick makes it much much easier, it means that a macro can get the `int` index corresponding to a given member very easily. And I guess this is why you added it? It's not really for utility for the user, it was just to help you implement the indexed visitors easily. (I think?)

Anyways, thanks for that. There's still some more work -- I need to implement `visit_struct::get` for the intrusive syntax, and also make the hana and fusion wrappers, and if that works on all the compilers then I'll probably merge it. If you have thoughts or comments they are welcome. I'm considering also trying to make a `std::tie` analogue.

**Comment by dcreager** [comment]
> You may be amused to learn, I have resurrected the "field_enum" in the develop branch.

Nice!

> And I guess this is why you added it? It's not really for utility for the user, it was just to help you implement the indexed visitors easily. (I think?)

Yes that's right!  It was most useful because the indexed visitor that used the enum was easier to understand (at least to me).  That said, I liked your suggestion of separating non-indexed and indexed visitation, instead of clumping them together in a single interface, and I don't think you can get that separation with the enum implementation.  (If you implement the indexed visitor via the non-indexed visitor, that is; if you do it the other way around I think you can use either approach.)

Anyway, all of it is hidden away behind the public interface so it's more of a philosophical discussion than anything!

**Pull request closed without merging**
